name: QIT Security Test
on:
  pull_request:
permissions:
  pull-requests: write
jobs:
  qit_activation:
    name: QIT Security
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable QIT development mode
        run: ./bin/qit dev
      - name: Connect to QIT Staging
        run: ./bin/qit env:add --environment=staging --manager_url=https://stagingcompatibilitydashboard.wpcomstaging.com --qit_secret=${{ secrets.QIT_STAGING_SECRET }}
      - name: Create Zip.
        run: docker run --rm --user $(id -u):$(id -g) -v "$GITHUB_WORKSPACE:/app" -w /app joshkeegan/zip:latest sh -c "zip -r automatewoo.zip automatewoo"
      - name: Produce output
        id: run-produce-output
        run: echo $(foo_output=./mimick-output.sh) >> $GITHUB_OUTPUT
      - name: Echo output
        if: always()
        run: echo ${{ steps.run-produce-output.outputs.foo_output }}
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          header: QIT Security Test
          message: |
            ```            
            ${{ steps.run-produce-output.outputs.foo_output }}
            
            ${{ steps.run-produce-output.outputs.stdout }}
            
            ${{ steps.run-produce-output.outputs.result }}
            
            ${{ steps.run-produce-output.outputs.stderr }}
            
            ${{join(steps.run-produce-output.outputs.*, '\n')}}
            ```