name: QIT Security Test
on:
  push
jobs:
  setup-qit:
    name: Setup QIT
    uses: ./.github/workflows/setup-qit.yml
    secrets: inherit
  qit_activation:
    name: QIT Security
    runs-on: ubuntu-20.04
    needs: [ setup-qit ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Zip.
        run: docker run --rm --user $(id -u):$(id -g) -v "$GITHUB_WORKSPACE:/app" -w /app joshkeegan/zip:latest sh -c "zip -r automatewoo.zip automatewoo"
      - name: Run Activation Test
        run: ./bin/qit run:security automatewoo --zip=automatewoo.zip --wait