name: Setup QIT
on:
  workflow_call
jobs:
  main:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Enable QIT development mode
        run: ./bin/qit dev
      - name: Connect to QIT Staging
        run: ./bin/qit env:add --environment=staging --manager_url=https://stagingcompatibilitydashboard.wpcomstaging.com --qit_secret=${{ secrets.QIT_STAGING_SECRET }}